language: android
android:
   components:
   - tools
   - platform-tools
   - android-24
   - build-tools-24.0.1
   - extra

jdk: oraclejdk8

notifications:
  email: false

sudo: false

script:
  - ./gradlew clean build